# Reference existing vnet
vnet_rg_name="atu045dev_rg"
vnet_name="atu045dev-VN"
subnet_name="atu045dev-oradb"
address_prefix="10.135.10.0/24"
#
location="West Europe"
rg_name="atu045-oradb-rg"
prefix="atu045oradb"
storage_acc="atu045oradbsa"
storage_type="Premium_LRS"
adminuser="atu045"
vmsize="Standard_DS3"
vmpublisher = "RedHat"
vmoffer = "RHEL"
vmsku = "7.3"
vmversion = "latest"
