# Reference existing vnet
vnet_rg_name="atu045dev_rg"
vnet_name="atu045dev-VN"
subnet_name="atu045dev-oradb1"
address_prefix="10.135.11.0/24"
#
location="West Europe"
rg_name="atu045-oradb1-rg"
prefix="atu045oradb1"
storage_acc="atu045oradb1sa"
storage_type="Premium_LRS"
adminuser="atu045"
vmsize="Standard_DS3_v2"
vmpublisher = "RedHat"
vmoffer = "RHEL"
vmsku = "7.3"
vmversion = "latest"
